# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/devices.ipynb.

# %% auto 0
__all__ = ['Device', 'AirPurifier', 'Fan', 'CeilingFan', 'TuyaAirPurifier']

# %% ../notebooks/devices.ipynb 1
from pydantic import BaseModel
from tuya_iot import TuyaOpenAPI

# %% ../notebooks/devices.ipynb 3
class Device:
    "Base class for all smart home devices"


class AirPurifier:
    "Air Purifier device"


class Fan(Device):
    "A Fan device"


class CeilingFan(Device):
    "A Fan that is attached to the ceiling"

# %% ../notebooks/devices.ipynb 6
class TuyaAirPurifier(BaseModel, AirPurifier):
    """Purifiers controlled by a Tuya Smart Switch"""

    device_id: str
    client_id: str
    client_secret: str
    country_code: str
    username: str
    password: str
    endpoint: str = "https://openapi.tuyaus.com"
    appschema: str = "smartLife"

    def __post_init__(self):
        self.client = TuyaOpenAPI(self.endpoint, self.client_id, self.client_secret)
        self.client.connect(
            self.username, self.password, self.country_code, self.appschema
        )

    def switch(self, on: bool = True):
        self.client.post(
            f"/v1.0/devices/{self.device_id}/commands",
            {"commands": [{"code": "switch_1", "value": on}]},
        )

    def turn_on(self):
        self.switch(True)

    def turn_off(self):
        self.switch(False)
