# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/00-dagster_repository.ipynb.

# %% auto 0
__all__ = ['tjhome']

# %% ../notebooks/00-dagster_repository.ipynb 1
from dagster import repository
from .air_quality import regulate_air_quality, regulate_air_quality_schedule


@repository
def tjhome():
    return [regulate_air_quality, regulate_air_quality_schedule]
