name: tjhome Automerge

on:
    pull_request:
        branches:
          - master
        paths:
          - 'dev/**'
          - 'pkgdown/**'
          - '_pkgdown.yml'
          - '**.md'
          - 'README.**'
          - 'CODEOWNERS'

jobs:
    build_package:
        name: Build the package
        runs-on: ubuntu-latest
        steps:
          - name: Exit with success
            run: exit 0
    test_package:
        name: Run unit tests
        runs-on: ubuntu-latest
        steps:
          - name: Exit with success
            run: exit 0
    test_coverage:
        name: Measure test coverage
        runs-on: ubuntu-latest
        steps:
          - name: Exit with success
            run: exit 0
    test_lintr:
        name: Linting
        runs-on: ubuntu-latest
        steps:
          - name: Exit with success
            run: exit 0
    test_spelling:
        name: Spell Check
        runs-on: ubuntu-latest
        steps:
          - name: Exit with success
            run: exit 0
