name: tjhome Deployment

on:
    push:
        branches:
          - master
        paths-ignore:
          - 'docs/**'

jobs:
    publish_and_deploy:
        name: Publish and Deploy tjhome
        runs-on: ubuntu-latest
        steps:
          - name: Checkout the code
            uses: actions/checkout@v2
            with:
                token: ${{ secrets.GHA_PAT }}
          - name: Login to Docker Hub
            run:  make dockerhub-login
            env:
                DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
                DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          - name: Retrieve the image
            run: make pkg-build-pull && make pkg-build
          - name: Publish the image
            run: make pkg-publish
          - name: Create Release
            run: make pkg-release
            env:
                GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
          - name: Deploy C66 Stack
            run: make pkg-deploy
            env:
                C66_DEPLOY_HOOK: ${{ secrets.C66_DEPLOY_HOOK }}
          - name: Deploy documentation
            run: make pkg-docs-deploy
