name: tjhome Testing

on:
    pull_request:
        branches:
          - master
        paths-ignore:
          - 'dev/**'
          - 'pkgdown/**'
          - '_pkgdown.yml'
          - '**.md'
          - 'README.**'
          - 'CODEOWNERS'
          - 'docs/**'

jobs:
    build_package:
        name: Build the package
        runs-on: ubuntu-latest
        steps:
          - name: Checkout the code
            uses: actions/checkout@v2
          - name: Login to Docker Hub
            run:  make dockerhub-login
            env:
                DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
                DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          - name: Build docker image
            run:  make pkg-build-pull && make pkg-build && make pkg-build-push
    test_package:
        name: Run unit tests
        runs-on: ubuntu-latest
        needs: build_package
        steps:
          - name: Checkout the code
            uses: actions/checkout@v2
          - name: Login to Docker Hub
            run:  make dockerhub-login
            env:
                DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
                DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          - name: Retrieve the image
            run: make pkg-build-pull && make pkg-build
          - name: Run unit tests
            run: make pkg-test
            env:
                GHA_JOB_ID: tpkg
    test_coverage:
        name: Measure test coverage
        runs-on: ubuntu-latest
        needs: build_package
        steps:
          - name: Checkout the code
            uses: actions/checkout@v2
          - name: Login to Docker Hub
            run:  make dockerhub-login
            env:
                DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
                DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          - name: Retrieve the image
            run: make pkg-build-pull && make pkg-build
          - name: Measure the test coverage
            run: make pkg-test-coverage
            env:
                GHA_JOB_ID: tcov
          - name: Archive test coverage
            uses: actions/upload-artifact@v1
            with:
                name: test-coverage
                path: /tmp/tjhome/test_coverage.zip
    test_lintr:
        name: Linting
        runs-on: ubuntu-latest
        needs: build_package
        steps:
          - name: Checkout the code
            uses: actions/checkout@v2
          - name: Login to Docker Hub
            run:  make dockerhub-login
            env:
                DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
                DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          - name: Retrieve the image
            run: make pkg-build-pull && make pkg-build
          - name: Run linting
            run: make pkg-test-linting
    test_spelling:
        name: Spell Check
        runs-on: ubuntu-latest
        needs: build_package
        steps:
          - name: Checkout the code
            uses: actions/checkout@v2
          - name: Login to Docker Hub
            run:  make dockerhub-login
            env:
                DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
                DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          - name: Retrieve the image
            run: make pkg-build-pull && make pkg-build
          - name: Run spell check
            run: make pkg-test-spelling
